# vi: set ft=ruby :

source "https://supermarket.chef.io"

cookbook "apt"
cookbook "ubuntu"
cookbook "build-essential"
cookbook "ntp"
cookbook "git"
cookbook "rvm", github: "martinisoft/chef-rvm"
cookbook "mono", github: "Youscribe/cookbook-mono"
cookbook "fsharp", path: "~/development/cookbooks/fsharp"
cookbook "dotfiles", path: "~/development/cookbooks/dotfiles"
cookbook "apache_spark"
cookbook "spark_wrapper", path: "~/development/cookbooks/spark_wrapper"
cookbook "hadoop"
cookbook "hadoop_wrapper", path: "~/development/cookbooks/hadoop_wrapper"
cookbook "eventstore"
cookbook "scala"
cookbook "java"
cookbook "simple-scala-sbt"
cookbook "anaconda"
cookbook "tachyon", path: "~/development/cookbooks/tachyon"
cookbook "anaconda_wrapper", path: "~/development/cookbooks/anaconda_wrapper"
cookbook "zookeeper"
cookbook "apache_kafka"
